### ISSUE TITLE
Mystery file

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/twxplorer#4]
I'm not sure why this file is in here.  
https://github.com/NUKnightLab/twxplorer/blob/master/twxplorer/fetch.py

**Comment by JoeGermuska** [comment]
hm. you're the one who committed it in cff6a40895ec7f0ba9c802f17f3a03ff47eccc0f

if it's not referenced anywhere else we can clobber it.

**Comment by jywsn** [comment]
removed
